### ISSUE TITLE
links to Oracle SDKs

### ISSUE THREAD

**Issue by user8547** [martinpaljak/ant-javacard#11]
Would be helpful if README.md would include link to https://github.com/martinpaljak/oracle_javacard_sdks repository.
Currently the reader has to figure out himself what does /path/to/jckit_dir1 means and where to get it.
The example build.xml can also be updated to include `jckit="oracle_javacard_sdks/jc222_kit/"`.

**Comment by martinpaljak** [comment]
Will update. Right now I assume that the reader is familiar with the overall ecosystem and can deduce the necessary information.

**Comment by martinpaljak** [comment]
Added a simple oneliner. This should be enough.
