### ISSUE TITLE
Build fails with bytecode errors

### ISSUE THREAD

**Issue by dwimberger** [martinpaljak/ant-javacard#12]
Tried to build with 1.6, 1.7 and 1.8 JDK's as well as JavaCard SDK 2.1.2, 2.2.1, 2.2.2, 3.0.4. Always with the same error on conversion (OS X 10.11.5):

      error: TestApplet: unhandled bytecode arraylength in clinit method, try a different compiler.
      error: TestApplet:unhandled bytecode i2b in clinit method, try a different compiler.

There is no static initializer in the applet.
Any idea what could be going wrong?

**Comment by martinpaljak** [comment]
Only if you can provide the source of the applet.

**Comment by martinpaljak** [comment]
ant-javacard is just a wrapper around the Oracle SDK components, if they mystically fail, so will ant-javacard. I can have a look but ...

**Comment by dwimberger** [comment]
Of course, you are right. The issue is not from the task, but rather from the converter itself.

**Comment by martinpaljak** [comment]
I've not encountered such error, so if you figure it out, it might be useful to know :)

**Comment by dwimberger** [comment]
It seems like using the length property of any array within the constructor causes the error.
It works normally in other methods, but I changed it to hard coded lengths anyway.

Thanks for your utilities btw. great work and really helpful.
