### ISSUE TITLE
Issue with white-space directory in Windows

### ISSUE THREAD

**Issue by jeffryang24** [martinpaljak/ant-javacard#16]
I got this error while verifying CAP file, but it was successfully compiling the source into CAP file.... 😄 

My OS and IDE detail:
-> Windows 10 Enterprise v1607 x64
-> Java Card SDK 2.2.2
-> Eclipse Neon.3
-> Ant-Javacard v1.7 (latest)

My build.xml:
![build.xml](http://i64.tinypic.com/2cd8g3d.png)

My build result:
![screenshot](http://i65.tinypic.com/14t341z.png)

I think there is a problem with whitespace-issue because it only shows C:\Users\Jeffry instead of C:\Users\Jeffry Angtoni\...

**Comment by martinpaljak** [comment]
Could you run ant with debug mode ?

**Comment by martinpaljak** [comment]
Nevermind. I can reproduce it but the obvious things to make the ant task parser do the right thing do not seem to work. will have to investigate a bit.

**Comment by jeffryang24** [comment]
Below is the output in verbose mode...
> C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello>ant -v
> Apache Ant(TM) version 1.10.1 compiled on February 2 2017
> Trying the default build file: build.xml
> Buildfile: C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\build.xml
> Detected Java version: 1.8 in: C:\Program Files\Java\jdk1.8.0_131\jre
> Detected OS: Windows 10
> parsing buildfile C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\build.xml with URI = file:/C:/Users/Jeffry%20Angtoni/Source/GitHub/java-card-tuts/Hello/build.xml
> Project base dir set to: C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello
> parsing buildfile jar:file:/C:/apache-ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/C:/apache-ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml from a zip file
> Build sequence for target(s) `main' is [clean, init, compile, cap, main]
> Complete build sequence is [clean, init, compile, cap, main, test-compile, test, ]
> 
> clean:
>    [delete] Deleting directory C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\bin
>    [delete] Deleting C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\bin\main\com\jeffry\sc\Hello.class
>    [delete] Deleting directory C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\bin\main\com\jeffry\sc
>    [delete] Deleting directory C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\bin\main\com\jeffry
>    [delete] Deleting directory C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\bin\main\com
>    [delete] Deleting directory C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\bin\main
>    [delete] Deleting directory C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\bin
>    [delete] Deleting directory C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\dist
>    [delete] Deleting C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\dist\HelloWorld.cap
>    [delete] Deleting directory C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\dist
> 
> init:
>     [mkdir] Created dir: C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\bin
> 
> compile:
>     [javac] com\jeffry\sc\Hello.java added as com\jeffry\sc\Hello.class doesn't exist.
>     [javac] Compiling 1 source file to C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\bin
>     [javac] Using modern compiler
>     [javac] Compilation arguments:
>     [javac] '-d'
>     [javac] 'C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\bin'
>     [javac] '-classpath'
>     [javac] 'C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\bin;C:\JavaCardSDK\2.2.2\lib\api.jar'
>     [javac] '-sourcepath'
>     [javac] 'C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\src\main'
>     [javac] '-target'
>     [javac] '1.8'
>     [javac] '-g:none'
>     [javac] '-source'
>     [javac] '1.8'
>     [javac]
>     [javac] The ' characters around the executable and arguments are
>     [javac] not part of the command.
>     [javac] File to be compiled:
>     [javac]     C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\src\main\com\jeffry\sc\Hello.java
> 
> cap:
>     [mkdir] Created dir: C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\dist
>       [get] Destination already exists (skipping): C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\libs\ant-javacard.jar
>  [javacard] JavaCard 2.2.2 SDK detected in C:/JavaCardSDK/2.2.2
>       [cap] INFO: using JavaCard v2.2.2 SDK in C:/JavaCardSDK/2.2.2
>       [cap] Setting package name to main.com.jeffry.sc
>       [cap] Building CAP with 1 applet from package main.com.jeffry.sc
>       [cap] main.com.jeffry.sc.Hello DADEDF000011
>   [compile] com\jeffry\sc\Hello.java added as com\jeffry\sc\Hello.class doesn't exist.
>   [compile] Compiling 1 source file to C:\Users\Jeffry Angtoni\AppData\Local\Temp\jccpro1397039895554653841
>   [compile] Using external javac compiler
>   [compile] Compilation arguments:
>   [compile] '-d'
>   [compile] 'C:\Users\Jeffry Angtoni\AppData\Local\Temp\jccpro1397039895554653841'
>   [compile] '-classpath'
>   [compile] 'C:\Users\Jeffry Angtoni\AppData\Local\Temp\jccpro1397039895554653841;C:\JavaCardSDK\2.2.2\lib\api.jar'
>   [compile] '-sourcepath'
>   [compile] 'C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\src\main'
>   [compile] '-target'
>   [compile] '1.5'
>   [compile] '-g'
>   [compile] '-Xlint'
>   [compile] '-Xlint:-options'
>   [compile] '-Xlint:-serial'
>   [compile] '-source'
>   [compile] '1.5'
>   [compile]
>   [compile] The ' characters around the executable and arguments are
>   [compile] not part of the command.
>   [compile] File to be compiled:
>   [compile]     C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\src\main\com\jeffry\sc\Hello.java
>       [cap] cmdline: "C:\Program Files\Java\jdk1.8.0_131\jre\bin\java.exe" -classpath C:\JavaCardSDK\2.2.2\lib\converter.jar;C:\JavaCardSDK\2.2.2\lib\offcardverifier.jar com.sun.javacard.converter.Converter -classdir "C:\Users\Jeffry Angtoni\AppData\Local\Temp\jccpro1397039895554653841" -d "C:\Users\Jeffry Angtoni\AppData\Local\Temp\jccpro2548572401104791438" -exportpath ;C:\JavaCardSDK\2.2.2\api_export_files -verbose -nobanner -out CAP -applet 0xDA:0xDE:0xDF:0x00:0x00:0x11 main.com.jeffry.sc.Hello main.com.jeffry.sc 0xDA:0xDE:0xDF:0x00:0x00 0.0
>       [cap] Executing 'C:\Program Files\Java\jdk1.8.0_131\jre\bin\java.exe' with arguments:
>       [cap] '-classpath'
>       [cap] 'C:\JavaCardSDK\2.2.2\lib\converter.jar;C:\JavaCardSDK\2.2.2\lib\offcardverifier.jar'
>       [cap] 'com.sun.javacard.converter.Converter'
>       [cap] '-classdir'
>       [cap] 'C:\Users\Jeffry Angtoni\AppData\Local\Temp\jccpro1397039895554653841'
>       [cap] '-d'
>       [cap] 'C:\Users\Jeffry Angtoni\AppData\Local\Temp\jccpro2548572401104791438'
>       [cap] '-exportpath'
>       [cap] ';C:\JavaCardSDK\2.2.2\api_export_files'
>       [cap] '-verbose'
>       [cap] '-nobanner'
>       [cap] '-out'
>       [cap] 'CAP'
>       [cap] '-applet'
>       [cap] '0xDA:0xDE:0xDF:0x00:0x00:0x11'
>       [cap] 'main.com.jeffry.sc.Hello'
>       [cap] 'main.com.jeffry.sc'
>       [cap] '0xDA:0xDE:0xDF:0x00:0x00'
>       [cap] '0.0'
>       [cap]
>       [cap] The ' characters around the executable and arguments are
>       [cap] not part of the command.
>       [cap] CAP saved to C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\dist\HelloWorld.cap
>    [verify] cmdline: "C:\Program Files\Java\jdk1.8.0_131\jre\bin\java.exe" -classpath C:\JavaCardSDK\2.2.2\lib\converter.jar;C:\JavaCardSDK\2.2.2\lib\offcardverifier.jar com.sun.javacard.offcardverifier.Verifier -nobanner C:\JavaCardSDK\2.2.2\api_export_files\java\io\javacard\io.exp C:\JavaCardSDK\2.2.2\api_export_files\java\lang\javacard\lang.exp C:\JavaCardSDK\2.2.2\api_export_files\java\rmi\javacard\rmi.exp C:\JavaCardSDK\2.2.2\api_export_files\javacard\framework\javacard\framework.exp C:\JavaCardSDK\2.2.2\api_export_files\javacard\framework\service\javacard\service.exp C:\JavaCardSDK\2.2.2\api_export_files\javacard\security\javacard\security.exp C:\JavaCardSDK\2.2.2\api_export_files\javacardx\apdu\javacard\apdu.exp C:\JavaCardSDK\2.2.2\api_export_files\javacardx\biometry\javacard\biometry.exp C:\JavaCardSDK\2.2.2\api_export_files\javacardx\crypto\javacard\crypto.exp C:\JavaCardSDK\2.2.2\api_export_files\javacardx\external\javacard\external.exp C:\JavaCardSDK\2.2.2\api_export_files\javacardx\framework\math\javacard\math.exp C:\JavaCardSDK\2.2.2\api_export_files\javacardx\framework\tlv\javacard\tlv.exp C:\JavaCardSDK\2.2.2\api_export_files\javacardx\framework\util\intx\javacard\intx.exp C:\JavaCardSDK\2.2.2\api_export_files\javacardx\framework\util\javacard\util.exp C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\dist\HelloWorld.cap
>    [verify] Executing 'C:\Program Files\Java\jdk1.8.0_131\jre\bin\java.exe' with arguments:
>    [verify] '-classpath'
>    [verify] 'C:\JavaCardSDK\2.2.2\lib\converter.jar;C:\JavaCardSDK\2.2.2\lib\offcardverifier.jar'
>    [verify] 'com.sun.javacard.offcardverifier.Verifier'
>    [verify] '-nobanner'
>    [verify] 'C:\JavaCardSDK\2.2.2\api_export_files\java\io\javacard\io.exp'
>    [verify] 'C:\JavaCardSDK\2.2.2\api_export_files\java\lang\javacard\lang.exp'
>    [verify] 'C:\JavaCardSDK\2.2.2\api_export_files\java\rmi\javacard\rmi.exp'
>    [verify] 'C:\JavaCardSDK\2.2.2\api_export_files\javacard\framework\javacard\framework.exp'
>    [verify] 'C:\JavaCardSDK\2.2.2\api_export_files\javacard\framework\service\javacard\service.exp'
>    [verify] 'C:\JavaCardSDK\2.2.2\api_export_files\javacard\security\javacard\security.exp'
>    [verify] 'C:\JavaCardSDK\2.2.2\api_export_files\javacardx\apdu\javacard\apdu.exp'
>    [verify] 'C:\JavaCardSDK\2.2.2\api_export_files\javacardx\biometry\javacard\biometry.exp'
>    [verify] 'C:\JavaCardSDK\2.2.2\api_export_files\javacardx\crypto\javacard\crypto.exp'
>    [verify] 'C:\JavaCardSDK\2.2.2\api_export_files\javacardx\external\javacard\external.exp'
>    [verify] 'C:\JavaCardSDK\2.2.2\api_export_files\javacardx\framework\math\javacard\math.exp'
>    [verify] 'C:\JavaCardSDK\2.2.2\api_export_files\javacardx\framework\tlv\javacard\tlv.exp'
>    [verify] 'C:\JavaCardSDK\2.2.2\api_export_files\javacardx\framework\util\intx\javacard\intx.exp'
>    [verify] 'C:\JavaCardSDK\2.2.2\api_export_files\javacardx\framework\util\javacard\util.exp'
>    [verify] 'C:\Users\Jeffry'
>    [verify] 'Angtoni\Source\GitHub\java-card-tuts\Hello\dist\HelloWorld.cap'
>    [verify]
>    [verify] The ' characters around the executable and arguments are
>    [verify] not part of the command.
>    [verify] Copyright 2005 Sun Microsystems, Inc. All rights reserved. Use is subject to license terms.
>    [verify] Verifying CAP file C:\Users\Jeffry
>    [verify] Error: File not found: C:\Users\Jeffry
>    [verify] Verification completed with 0 warnings and 1 error.
> 
> BUILD FAILED
> C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello\build.xml:64: Java returned: 2
>         at org.apache.tools.ant.taskdefs.Java.execute(Java.java:115)
>         at pro.javacard.ant.JavaCard$JCCap.execute(Unknown Source)
>         at pro.javacard.ant.JavaCard.execute(Unknown Source)
>         at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
>         at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
>         at org.apache.tools.ant.Task.perform(Task.java:348)
>         at org.apache.tools.ant.Target.execute(Target.java:435)
>         at org.apache.tools.ant.Target.performTasks(Target.java:456)
>         at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
>         at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
>         at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
>         at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
>         at org.apache.tools.ant.Main.runBuild(Main.java:857)
>         at org.apache.tools.ant.Main.startAnt(Main.java:236)
>         at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
>         at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
> 
> Total time: 3 seconds
> 
> C:\Users\Jeffry Angtoni\Source\GitHub\java-card-tuts\Hello>

**Comment by jeffryang24** [comment]
I already fix the JavaCardPro.java here. I added the double-quote sign, so the cli will assume this is a full path...
![change](http://i.imgur.com/MlGWG9i.png)

The test result goes here:
[ant-javacard-success-verbose.txt](https://github.com/martinpaljak/ant-javacard/files/1024386/ant-javacard-success-verbose.txt)
