### ISSUE TITLE
Don't show "int" warning when "ints=true"

### ISSUE THREAD

**Issue by 0xbaadf00d** [martinpaljak/ant-javacard#18]
Hello,

Is it possible to hide these warnings when the build.xml explicitely contains `ints=true` ?

```
[cap] warning: line 34: offlinewallet.Utils: int type of local variable.
[cap] warning: line 35: offlinewallet.Utils: int type of local variable.
[cap] warning: line 36: offlinewallet.Utils: int type of local variable.
[cap] warning: line 37: offlinewallet.Utils: int type of local variable.
[cap] warning: This package requires int support.
```

**Comment by martinpaljak** [comment]
Good question, will have to investigate, the int support has not been heavily tested.

**Comment by martinpaljak** [comment]
It seems that the "-nowarn" option only removes the final "[cap] warning: This package requires int support." but not the previous lines, so adding a new option to tweak the -nowarn flag is not justified. You must ignore these lines.
