### ISSUE TITLE
Which JavaCard SDK version to use?

### ISSUE THREAD

**Issue by 0xbaadf00d** [martinpaljak/ant-javacard#19]
Hello,

I have some JavaCard running on version 2.2 and 2.3. What is the best practive ?  I have to use the SDK 305u1 or the 222 ? Both running on my cards, but the CAP file is twice bigger with the 305u1 (12kB against 5kB).

Is new version is more secure and fix issue ?

Sincerly.

**Comment by martinpaljak** [comment]
The cap file with v3 SDK-s also includes elements that will not be sent to the card (class files themselves, inspect the .cap with `jar tvf capfile`) so the size does not really matter. Use `gp -v -cap <capfile>` from GlobalPlatformPro to get a hint about code size to be sent to the card (actual on-card resource usage depends on platform):

```
$ gp -v -cap Empty221.cap | grep "code size"
Total code size: 198 bytes (704 with debug)
$ gp -v -cap Empty305.cap | grep "code size"
Total code size: 186 bytes (254 with debug)
```

You can use the oldest SDK that has all the API versions you care about. If that is 222, use 222. As a general rule, later is greater ;)
