### ISSUE TITLE
Error when importing multiple package with the same path

### ISSUE THREAD

**Issue by RESTful-web-dev** [martinpaljak/ant-javacard#24]
Hello,

I got an error when using multiple imports with the same folderpath.

I did some modifications to source code to support it. I tried to do a branch to push my modifications but I don't have the rights. Is there a prefered way to share modifications ?

Cheers and thanks for this wonderful project that saved me hours of coding ;-)

**Comment by martinpaljak** [comment]
Make a fork and a pull request.

**Comment by RESTful-web-dev** [comment]
Thanks ;-) It's done
