### ISSUE TITLE
Feature request: support for reproducible builds

### ISSUE THREAD

**Issue by promovicz** [martinpaljak/ant-javacard#28]
Currently the Sun/Oracle CAP generator inserts a timestamp in the CAP-file manifest that makes builds non-reproducible.

It should be possible to fix this in a generic and reusable manner by re-generating the JAR with this attribute squashed.

Apart from this little issue the tools involved seem to behave reproducibly already.

**Comment by martinpaljak** [comment]
`gp -cap <blah.cap> -info` will give you the code hash. Isn't that sufficient?

**Comment by martinpaljak** [comment]
I am not against it, just that it might not make much practical sense. Feel free to come up with a *configurable* patch. DAP in GlobalPlatform is more likely something that makes sense for what you have in mind, I find the metadata in the generated .cap useful. Reproducible builds are nice for software, where you can verify what is running (like a PC). JavaCard-s provide something different than file hashes for verification.

**Comment by martinpaljak** [comment]
And "Load File Data Block Hash" (GP 2.2 section 9.2) is exactly what you want to check (and is what is signed for DAP)

**Comment by promovicz** [comment]
I share the viewpoint that this should be configurable and default to off.

About DAP: can that be used in practice without signing vendor NDAs? My impression was that this is only available if you use proprietary features to reconfigure the card, but I might have missed some critical feature while reading the GP specs.

My reasons for not wanting to use NDA-bound procedures are manifold, both in open and shared source environments (the latter is what I do commercially - sharing code with customers). I want to provide this openness without forcing NDAs upon everyone involved in verification.

**Comment by martinpaljak** [comment]
YMMV. This is described in public specs but depends on cards and features and vendors. GPPro should get some code to work with this in near future.

**Comment by martinpaljak** [comment]
Also - the hash of the applet only really matters during loading (after what it becomes "invisible"), which means that one *needs* to have special tools at hand (that perform loading, such as GPPro).

Anyway - I will happily include a patch that adds this feature unless it is too surgical/fragile or too much hassle/new code. The RightSolution(tm) for this problem IMHO is load file data hash and DAP, if necessary.

**Comment by bjornfor** [comment]
+1 for built-in support for reproducible builds. (I currently run ant under libfaketime.)

**Comment by martinpaljak** [comment]
The next version of ant-javacard shall introduce "name templates" and one variable for generating output file names (included in default template) shall be `%h` for load file data block hash prefix (or `%H` for the full hash). I think that going through the trouble of hiding build timestamps from an otherwise deterministic build process (for the useful content - what gets loaded to the card) is not worth the trouble.

https://github.com/martinpaljak/capfile can also show the load file data block hash and allows to generate DAP signatures over the same hash, so eventually this should be something of interest _and_ practical value to developers and users (DAP is the only way to actually enforce the result of the reproducible build on the card)

```
$ shasum Empty_0102030405_fca23276_3.0.4.cap
831ec8801fc79152d1fc506b2c2319ae67d4c8c9  Empty_0102030405_fca23276_3.0.4.cap
$ capfile Empty_0102030405_fca23276_3.0.4.cap 
CAP file (v2.1), contains: applets for JavaCard 3.0.4
Package: testapplets.empty 0102030405 v0.0
Import: javacard.framework A0000000620101 v1.5
Import: javacard.security A0000000620102 v1.5
Import: java.lang A0000000620001 v1.0
Applet: testapplets.empty.Empty 0102030405060708
Generated by Oracle Corporation converter  [v3.0.4]
On Tue Sep 18 14:10:45 EEST 2018 with JDK 1.8.0_181 (Oracle Corporation)
Total code size: 211 bytes (283 with debug)
SHA256 (code): FCA23276C05636F7F51AC296AFCAC8C7658F47B1F0881ECF7DB0E69409E59A36
SHA1   (code): C6B556CCF06B8EFF9B8B0489B0E9CFF694CF2E41
$ rm Empty_0102030405_fca23276_3.0.4.cap
$ ant test
... # output removed
$ shasum Empty_0102030405_fca23276_3.0.4.cap
272c9463ee7b778436c65261e7de206a2cc446ee  Empty_0102030405_fca23276_3.0.4.cap
$ capfile Empty_0102030405_fca23276_3.0.4.cap 
CAP file (v2.1), contains: applets for JavaCard 3.0.4
Package: testapplets.empty 0102030405 v0.0
Import: javacard.framework A0000000620101 v1.5
Import: javacard.security A0000000620102 v1.5
Import: java.lang A0000000620001 v1.0
Applet: testapplets.empty.Empty 0102030405060708
Generated by Oracle Corporation converter  [v3.0.4]
On Mon Sep 24 20:41:18 EEST 2018 with JDK 1.8.0_181 (Oracle Corporation)
Total code size: 211 bytes (283 with debug)
SHA256 (code): FCA23276C05636F7F51AC296AFCAC8C7658F47B1F0881ECF7DB0E69409E59A36
SHA1   (code): C6B556CCF06B8EFF9B8B0489B0E9CFF694CF2E41
```

**Comment by martinpaljak** [comment]
#45 includes a different approach to the problem. Hopefully this is sufficient. capfile allows to make the most common signatures - 1k RSA - for DAP and GPPro allows to load such CAP-s. Support for ECC signatures is also coming to GPPro.
