### ISSUE TITLE
1.5 is no longer supported. Use 1.6 or later.

### ISSUE THREAD

**Issue by 424778940z** [martinpaljak/ant-javacard#31]
[compile] error: Source option 1.5 is no longer supported. Use 1.6 or later.
[compile] error: Target option 1.5 is no longer supported. Use 1.6 or later.

change this to 1.6 will solve the issue

https://github.com/martinpaljak/ant-javacard/blob/ee3de2443a6fdfdf95ac79f58f59efc6f9e38fd3/src/main/java/pro/javacard/ant/JCKit.java#L99

**Comment by benbenbenbenbenben** [comment]
Why was this issue closed? Should we use a preferred JDK version instead?

**Comment by martinpaljak** [comment]
Use a more recent converter with targetsdk option.

**Comment by Stroumph** [comment]
Hi,

I have a similar problem with Java 13.0.1, ant 10.1.7 and Java Card SDK 3.0.5u3.

I'm trying to build the Java Card Helloworld example as:

```ant
    <javacard jckit="${JC305}">
      <!-- Hello World Applet -->
      <cap targetsdk="${JC222}" aid="48656C6C6F576F726C64" package="helloworld" 
           version="1.0" output="build/helloworld.cap" sources="src/helloworld">
        <applet class="helloworld.HelloWorld" aid="48656C6C6F576F726C64417070"/>
      </cap>
    </javacard>
```
The ant constant value `${JC305}` points out javacard 3.0.5u3 sdk folder and `${JC222}` constant value the Javacard 2.2.2 sdk folder.

After an `ant build`, I have this error:

```shell
build:
      [cap] INFO: using JavaCard 3.0.5 SDK in /home/stroumph/work/TP-Java_Card/applets/sdks/jc305u3_kit
      [cap] INFO: targeting JavaCard 2.2.2 SDK in sdks/jc222_kit
      [cap] Building CAP with 1 applet from package helloworld (AID: 48656C6C6F576F726C64)
      [cap] helloworld.HelloWorld 48656C6C6F576F726C64417070
  [compile] Compiling files from /home/stroumph/work/TP-Java_Card/applets/src/helloworld
  [compile] Compiling 1 source file to /tmp/jccpro13153822473430201991
  [compile] error: Source option 6 is no longer supported. Use 7 or later.
  [compile] error: Target option 6 is no longer supported. Use 7 or later.
```

**Comment by asdfjkl** [comment]
@Stroumph Were you able to fix that? I am running into the same problem here...

**Comment by martinpaljak** [comment]
@asdfjkl Match your javacard kit with the right JDK, based on https://github.com/martinpaljak/ant-javacard/wiki/Version-compatibility

**Comment by martinpaljak** [comment]
Will have to amend the readme as this is a common isaue

**Comment by asdfjkl** [comment]
@martinpaljak Thanks very much for explaining. The error message was difficult to interpret for me...

**Comment by asdfjkl** [comment]
@martinpaljak Thanks, again. 
If there is someone struggling like myself, and until there is a tutorial, just a quick note / explanation. In my setup I wanted to use an old javacard, which has only 2.2.2. Here is my build.xml.

Essentially:

- linked the jc 2.2.2 extlibs in the project (this is just to ensure that eclipse doesn't underline all code)
- set javacrad kit to 3.0.4 (libs in subdir /extlib/jc304_kit)
- set targetsdk to 2.2.2 (libs in subdir /extlib/jc222_kit) 

````
<?xml version="1.0" encoding="UTF-8"?>
<project basedir="." default="buildcap" name="Hello-World-Applet">
  <!-- Applet building dependencies -->

  <property name="JC222" value="extlibs/jc222_kit"/>
  <property name="JC304" value="extlibs/jc304_kit"/>

   
  <!-- ant-javacard task from javacard.pro -->
  <taskdef name="javacard" classname="pro.javacard.ant.JavaCard" classpath="tools/ant-javacard.jar"/>
  
  <!-- target javacard 2.2.2 -->
  <target name="buildcap">
  	<delete file="cap/hw.cap"/>
    <!-- <javacard jckit="extlibs/jc222_kit/"> -->
  	<javacard jckit="${JC304}">
      <cap targetsdk="${JC222}" output="cap/hw.cap" aid="D276000132" sources="src">
        <applet class="de.asdfjkl.helloworld.javacard.MainApplet" aid="D27600013268776F"/>
      </cap>
    </javacard>
  </target>
 	
 <!-- Install Applet -->
 <target name="install" depends="buildcap"> 
    <exec executable="/bin/bash">
  	  <arg value="scripts/install+personalize.sh"/> 
  	</exec> 
 </target> 
	
</project>
````

PS: I think it would be nice to have some (maybe one for 2.2.2, one for 3.0.4, one for 3.0.5 as these three seems to cover most typical cards out there, at least the ones I encountered) demo/sample projects + tutorial, that can be easily imported into eclipse. @martinpaljak  In case you agree, I'd be willing to contribute some...

**Comment by asdfjkl** [comment]
Just fyi, I've added a JavaCard Hello World + tooling howto using GPPro and ant-javacard @ https://github.com/asdfjkl/JCHelloWorld
