### ISSUE TITLE
Build process leaves temporary directory in place

### ISSUE THREAD

**Issue by lumag** [martinpaljak/ant-javacard#4]
Ant doesn't support removing temporary directories recursively, so after building the ant-javacard, the temorary directory still exists:

```
dist:
      [jar] Building jar: /home/lumag/Projects/JC/ant-javacard/ant-javacard.jar

BUILD SUCCESSFUL
Total time: 1 second
[pid 29960] unlink("/tmp/jcpro1902514858") = -1 EISDIR (Is a directory)
[pid 29960] rmdir("/tmp/jcpro1902514858") = -1 ENOTEMPTY (Directory not empty)
```

and

```
$ ls -ld /tmp/jcpro1902514858/
drwxr-xr-x 3 lumag lumag 4096 июл 30 15:30 /tmp/jcpro1902514858/
```

**Comment by martinpaljak** [comment]
Correct. Thanks for noticing!

**Comment by lumag** [comment]
@martinpaljak Note. This issue is unrelated to #5 and isn't closed. Ant still creates temporary directories when building ant-javacard. Please reopen.

Note: I do not know any good way to solve this issue if you don't want to have the classes folder.
