### ISSUE TITLE
Java Compiler Compliance option missing

### ISSUE THREAD

**Issue by gitfineon** [martinpaljak/ant-javacard#41]
For reference: https://github.com/martinpaljak/ant-javacard/pull/26#issuecomment-408608499
First of all, I am new to JavaCards and not experienced with java build tools, so far.

"Java Compiler Compliance" is used to compile for a JVM, which does not support the recent class file format, right? https://stackoverflow.com/questions/22584427/what-is-compiler-compliance-level-in-eclipse

Real cards or a simulator may have a compliance level lower than the compiler, but we have to make sure it runs properly.

> Sometimes the JCOP tools have hard time compiling/producing your applets (everything works fine, but the CAP file is not produced and cannot be uploaded to the card). The Java language compatibility needs to be set up properly for the Java Card project. In project properties in Eclipse chose "Java compiler" and set "Compiler compliance level" to 1.3 (this should be the safest).

Source: https://www.cs.ru.nl/E.Poll/hw/practical.html

I found similar configuration in this gradle build file. https://github.com/ANSSI-FR/SmartPGP/commit/9955dd92e1c367cbc887ce3ca53ac72294801e6a

Why do you think this option is obsolete?

**Comment by martinpaljak** [comment]
I guess the comment from the README is valid here:

The only supported Java version for all SDK targets is 1.8!

Am I missing something?

**Comment by gitfineon** [comment]
I do not request to use an older compiler version to compile [ant-javacard](https://github.com/martinpaljak/ant-javacard), which is forced to be 1.8 https://github.com/martinpaljak/ant-javacard/blob/2cce3ce619843208e22e7ab0bcc13b78d80e31f9/build.xml#L6

I'd like to manually choose javaversion for a *.cap file. But then I found https://github.com/martinpaljak/ant-javacard/pull/26#issuecomment-385625435 where you argued: 

> FYI: After giving it some thought, I removed javaversion from <javacard>, as this **feels like a very specific tweak**, which should not "pollute" the absolute minimum required possible configurable, which is the javacard kit.

I am a bit confused now. You answered supported target version is 1.8 only, but there is a function called [getJavaVersion()](https://github.com/martinpaljak/ant-javacard/blob/41d0816d495e3f47cf5a5b9601fdf7025405c943/src/main/java/pro/javacard/ant/JCKit.java#L106) which selects a java version based on the selected JC DevKit version. And 1.6 is the version selected for the latest JC DevKit, 1.5 for V222 and 1.2 for V221. 

Btw, why is the oldest 1.1 selected by default? I guess default should be latest?

The README states I can manually overwrite this, by using `javaversion` option, which I expect to set
https://github.com/martinpaljak/ant-javacard/blob/92cd7f4f13def01e7967495f3ddfedecc9dc9cd3/src/main/java/pro/javacard/ant/JavaCard.java#L507-L508

But this is the option, which is no longer available as you mentioned in https://github.com/martinpaljak/ant-javacard/pull/26#issuecomment-385625435. 

I was able to compile my project. But I guess the option is still useful to manually override!

**Comment by martinpaljak** [comment]
The option is available (as documented) for a single `<cap>` tag, not for `<javacard>` (can contain multiple <cap>-s)

Why do you need to change it? You might be interested in using the `targetsdk` option instead, as the maximum class file version supported by the converter in a given SDK is fixed?

**Comment by martinpaljak** [comment]
Unless there is a PR to create, I think this issue could be closed. I don't see what to change, maybe update docs somehow?

**Comment by gitfineon** [comment]
Arrg, the problem was switching back and forth. I did a checkout on the old version, added the `javaversion` thing and then using the current version showed me a "doesn't support attribute" message. Did not recognize the feature is documented for `<cap>`, only!

I tested both, `javaversion` and `targetsdk` but only the second one fixes my issue, thank you for that.

Is it necessary to have installed both JC SDKs? Or do you only parse the version string from the targetsdk?

**Comment by martinpaljak** [comment]
The recommended way is to use as recent SDK as possible for "running" (the `jckit` attribtue and reference the `targetsdk` for the intended target platform. You need to specify the full target SDK path, not just the version.
