### ISSUE TITLE
install LibraryUser_01020304050607_JCv2.2.2.cap

### ISSUE THREAD

**Issue by johnnytshi** [martinpaljak/ant-javacard#43]
How do you install "**LibraryUser_01020304050607_JCv2.2.2.cap**"?

If I install the cap file directly, I get: 
**LOAD failed: 0x6438**

So I tried to install "**testapplets.library.cap**" first (which works), then install the "**LibraryUser_01020304050607_JCv2.2.2.cap**", I get:
**CAP loaded
INSTALL [for install and make selectable] failed: 0x6985 (Conditions of use not satisfied)**

thanks!

**Comment by johnnytshi** [comment]
I am using **GlobalPlatformPro**

.\gp.exe -install .\testapplets.library.cap
.\gp.exe -install .\LibraryUser_01020304050607_JCv2.2.2.cap

**Comment by martinpaljak** [comment]
Please ignore this issue. The AID-s are overlapping (as they are just used for testing building, not for testing loading to actual cards). Make sure the AID-s are right for both library and library user and all should be good (if it is installable on a given card)

I'm shortly publishing a bigger update to ant-javacard (and the small capfile library)
