### ISSUE TITLE
Feature Request : Cap to IJC 

### ISSUE THREAD

**Issue by deekumar1211** [martinpaljak/ant-javacard#48]
We can include feature which can Convert Cap to IJC file to be loaded onto card. As IJC is much lighter version to be used on real card. 
I have complete the code to convert cap to ijc, If you are okay we can integrate with current code.

**Comment by martinpaljak** [comment]
If you have a PR to make, please do. Then we can have a look at actual code and how that would look like to users.

**Comment by martinpaljak** [comment]
https://help.github.com/articles/about-pull-requests/
