### ISSUE TITLE
Upload latest version to MVN repository

### ISSUE THREAD

**Issue by skrisztian** [martinpaljak/ant-javacard#50]
Great tool! Thanks for making it!

The current version in https://mvnrepository.com/artifact/com.github.martinpaljak/ant-javacard (18.07.12) still does not support the targetsdk parameter in the cap tag, I guess it is lagging behind the one on github. Could you push up the very latest version?

**Comment by martinpaljak** [comment]
Sure, in todo for upcoming week.

**Comment by martinpaljak** [comment]
There you go. Updated setup and configs so that it would happen whenever releasing in the future. http://central.maven.org/maven2/com/github/martinpaljak/ant-javacard/18.09.25/
