### ISSUE TITLE
Cap option 'javaversion' produces error 

### ISSUE THREAD

**Issue by tomasz-ondrusz-chyp** [martinpaljak/ant-javacard#52]
In my usage I am trying to specify java 1.5 as the compiler option. In the documentation, it mentions that javaversion should be an option of the cap tag in the build.xml file.

I have tried setting this at other levels (e.g. at taskdef or javacard), but neither option seems to work. I am sure that I am missing something obvious, but not sure what.

**Comment by martinpaljak** [comment]
If you try to use a more recent language options than what is by default supported by your target SDK, you should use the latest SDK (`jckit=` 3.0.5u3) for compilation and specify your target platform with `targetsdk=`2.2.2.

Other than that, please provide a full log with `ant --debug`

**Comment by martinpaljak** [comment]
On another thought, I'll remove javaversion and will rely on the automagic setting of the source and target versions with target and build SDK-s.
