### ISSUE TITLE
document private maven repo

### ISSUE THREAD

**Issue by ph4r05** [martinpaljak/ant-javacard#63]
Hi, 

I am using your libs and would like to bump to the v20 but they are not released in the maven central yet. Do you pls plan to submit it there?

Thanks!

**Comment by martinpaljak** [comment]
They are available from https://javacard.pro/maven/ and I will make occasional major milestone pushes to central as well, but when/by which criteria, not sure. The manual (pgp) and slow upload process is the obstacle.

**Comment by ph4r05** [comment]
Ah ok, thanks! Another thing - I noticed there are only several releases in the javacard.pro/maven. Do you delete old releases? If I use now ant-javacard:20.03.25 and gp 20.04.14 versions, which are currently present, do you think the artifacts will be there also 4 months later? Thanks!

**Comment by martinpaljak** [comment]
I do not intend to remove anything. As said, my plan is to push 4ish times a year to maven central exactly for that purpose (ease of finding and “central guarantees”) but no exact plan or scheme yet. For the fast and frequent tags the repo shall be the private one.

**Comment by martinpaljak** [comment]
Obviously I should document the presence of the repo but the splendid corona house arrest has left exactly “this much” free time next to home school and other weird things ...
