### ISSUE TITLE
StringPool & StringDef not working as expected

### ISSUE THREAD

**Issue by 0x2b3bfa0** [martinpaljak/ant-javacard#75]
It looks like classes generated with the [`StringPool`](https://docs.oracle.com/en/java/javacard/3.1/jc_api_srvc/api_classic/javacardx/annotations/StringPool.html) and [`StringDef`](https://docs.oracle.com/en/java/javacard/3.1/jc_api_srvc/api_classic/javacardx/annotations/StringDef.html) annotations aren't reachable from the annotated class, and tests don't cover this “edge” case:

https://github.com/martinpaljak/ant-javacard/blob/94897ceb903f443fc4f622e91207b013ac6b1005/src/testapplets/stringdefs/Empty.java#L10-L13

If the [`stringdefs` test case](https://github.com/martinpaljak/ant-javacard/blob/94897ceb903f443fc4f622e91207b013ac6b1005/tests-1.8.xml#L94-L101) included a call to [`HelloWorldString.importLibConstants`](https://docs.oracle.com/en/java/javacard/3.1/jc_api_srvc/api_classic/javacardx/annotations/StringPool.html) or tried to access any of the created fields from the [applet's class constructor](https://github.com/martinpaljak/ant-javacard/blob/94897ceb903f443fc4f622e91207b013ac6b1005/src/testapplets/stringdefs/Empty.java#L17-L19), the build process would fail:

```
Buildfile: /···/build.xml

clean:
   [delete] Deleting directory /···/build

jcpro:
    [mkdir] Created dir: /···/build
    [javac] Compiling 2 source files to /···/build

···:
      [cap] INFO: using JavaCard 3.1.0 SDK in /···/sdks/jc310r20210706_kit
      [cap] INFO: Setting package name to testapplets.stringdefs
      [cap] Building CAP with 1 applet from package testapplets.stringdefs (AID: 0102030405)
      [cap] testapplets.stringdefs.Empty 010203040506
  [compile] Compiling files from /···/src/testapplets/stringdefs
  [compile] Compiling 1 source file to /···
  [compile] /···/src/testapplets/stringdefs/Empty.java
  [compile] /···/src/testapplets/stringdefs/Empty.java:18: error: cannot find symbol
  [compile] 		HelloWorldString.importLibConstants();
  [compile] 		^
  [compile]   symbol:   variable HelloWorldString
  [compile]   location: class Empty
  [compile] 1 error

BUILD FAILED
/···: Compile failed; see the compiler error output for details.

Total time: 1 second
```

**Comment by 0x2b3bfa0** [comment]
It turns out that the processor is not being called for versions other than 3.04:

https://github.com/martinpaljak/ant-javacard/blob/bb4b6f2f722bddb0e66137c4d54dd4d83138359d/src/main/java/pro/javacard/ant/JavaCard.java#L554

**Comment by martinpaljak** [comment]
Will make a functional test case for it.

**Comment by martinpaljak** [comment]
This is fixed in #76 / [next](/martinpaljak/ant-javacard/tree/next) but releasing will depend on some structural rearrangements in capfile/globalplatformpro

**Comment by martinpaljak** [comment]
Fixed in master

**Comment by 0x2b3bfa0** [comment]
Thank you very much!

**Comment by martinpaljak** [comment]
There's also https://github.com/martinpaljak/ant-javacard/releases/tag/v23.03.21 but that release is buggy, updated release scripts and will try again in a day or two.
