### ISSUE TITLE
error: unsupported class file format of version 52.0.

### ISSUE THREAD

**Issue by Bianca988** [martinpaljak/ant-javacard#78]
Hi

I am using JDK 8 and javac -1.8. I also tried with JDK 11
I try to convert the file to a .CAP file but every time I run ant I receive the following error : error:  unsupported class file format of version 52.0.
Here is a snippet of my error : 
<img width="952" alt="image" src="https://user-images.githubusercontent.com/64011826/158370377-1bfc1c7d-a2bb-4fe8-ad20-2936d39b41a7.png">
Also, here is a snippet of my build.xml.  I tried several versions of the SDK. 
<img width="943" alt="image" src="https://user-images.githubusercontent.com/64011826/158370517-b8a310d7-2a5f-462d-969b-14c001c4acda.png">

Thank you!

**Comment by martinpaljak** [comment]
Only post text logs please. No screenshots. Also look at samples in https://github.com/martinpaljak/ant-javacard/blob/master/tests-1.8.xml and I recommend to start again from scratch. If you don't need any options, don't specify them or you have to know what you are doing.

You can see targeting information and which SDK to use with which JDK here: https://github.com/martinpaljak/ant-javacard/wiki/Version-compatibility

**Comment by HColt** [comment]
Hello @Bianca988 ,
I got the same issue during convert phase.
This is linekd to the java compiler version used.
You can force the correct Java version during compilation using 'target' option.
With JCDK 3.0 I force the target to 6 for javac compile rule as below:
<javac srcdir="./src" **target="6"** includes="**/*.java" destdir="${build.classes}" classpath="${jc.jar};${jc_ETSI_TS_102.241.jar}"/>

**Comment by Bianca988** [comment]
Hello @HColt 

Thank you for your reply. I understand what you are saying. Due to the fact that I already tried a lot of things ( some of them bad ) for that file and @martinpaljak's answer, I decided to start from scratch. It worked and I didn't even receive that error again. I will keep your advice in mind though.
