### ISSUE TITLE
Using with eclipse expects full paths

### ISSUE THREAD

**Issue by metsma** [martinpaljak/ant-javacard#8]
```
     <javacard jckit="ext/java_card_kit-2_2_2">
        <cap aid="00:00:00:00" version="3.5" output="applet.cap" classes="tmp">
            <applet class="applet.applet" aid="00:00:00:00"/>
            <import exps="ext/visa_openplatform-2_0" jar="ext/visa_openplatform-2_0/visaop20.jar"/>
        </cap>
     </javacard>
```

Gives error

[javacard] JavaCard SDK folder ext/java_card_kit-2_2_2 does not exist!
and
[cap] error: export file openplatform.exp of package visa.openplatform not found.

**Comment by martinpaljak** [comment]
It has been impossible to replicate this issue, but leaving open as it actually happens on a specific machine (OSX)

**Comment by RESTful-web-dev** [comment]
I also have this problem. The java card kit is found, but not the exps of GlobalPlatform.

> [cap] error: export file globalplatform.exp of package org.globalplatform not found.

I'm using Win10 with Ant 1.10.1

Really strange as the "-exportpath" contains the needed path.

Does anyone knows what going wrong ?

**Comment by RESTful-web-dev** [comment]
Finally found where was the problem !

My EXPs were not at the good place.

I also found a bug when importing multiple JARs/EXPs. I open an issue to describe it.

**Comment by martinpaljak** [comment]
Usage via eclipse is not a high priority in the first place. But closing until this can be reproduced.
