### ISSUE TITLE
Offcardverifier doesn't seems to be run on javacard sdk 2.2.2

### ISSUE THREAD

**Issue by vletoux** [martinpaljak/ant-javacard#9]
While testing the javacardos jcide, I got an error when building my applet:
com.sun.javacard.offcardverifier.bf: the number of interface for the class or interface XXX is incoherent with the number of the same class or same interface than the class component.

I was able to trigger the problem by not inheriting an interface.
Not OK:
public class MyPIN extends OwnerPIN {
OK:
public class MyPIN extends OwnerPIN implements PIN {

But when built under ant-javacard, no error is shown.
=> is ant-javacard really runing offcardverifier like the sdk built ?

**Comment by martinpaljak** [comment]
By default only converter is run. But that's a good feature request, having verify="true" for the cap element.

**Comment by martinpaljak** [comment]
Release 1.5 supports verification (off by default). Thanks for the tip!

**Comment by vletoux** [comment]
You forgot to update the link on the README (1.4 instead of 1.5)
I'll be happy to know if you succeed in the "deploy" step of travis which I see on the script, but not on bintray or other repository.
FYI: I integrated your software in the build process of the gidsApplet. Maybe you can get inspired from this.
https://github.com/vletoux/GidsApplet

**Comment by martinpaljak** [comment]
Good catch, updated the README.

Do you mean you'd like to be notified of successful release builds from Travis?

Regarding your build.xml: you don't have to specify the path to the actual class source folder, just sources="src" is enough. In fact, I think I'll make it default to "src" if not specified.

**Comment by vletoux** [comment]
No, I'd like to collect the built arctifact like Appveyor can do. 
Saw this: https://docs.travis-ci.com/user/deployment/bintray
